### ISSUE TITLE
Secrets handling

### ISSUE THREAD

**Issue by torivara** [matsest/bicep-registry-demo#1]
Hi!

Nice repository and good explanations! I have forked the content, and is trying the code in my own repo at the moment.

I would just like to point out that the practice of using structured data as secret is not the preferred way for GitHub. See [this](https://docs.github.com/en/actions/security-guides/encrypted-secrets#naming-your-secrets) section on naming your secrets. Putting structured data in secrets might prevent redaction of sensitive values in the logs.

Just wanted to comment on it, and you can decide for yourself if it is worth changing 🙂

Thank you for sharing this demo repository! 🙂

**Comment by torivara** [comment]
You could use one secret for AppId, one for AppSecret, and one for SubscriptionId, and use them in a shell task for logging in with az cli. Or you could create a custom action to authenticate with those three environment variables.

I fully understand that this is a demo, and as such I guess json secret is the simplest method for achieving CI/CD here. Maybe worth mentioning in the readme file or something?

**Comment by matsest** [comment]
Thank you @torivara  😃 

I've based the guidance on what the official [Azure login action suggests](https://github.com/Azure/login/#configure-a-service-principal-with-a-secret). The implementation of the action uses a [specific secret parser](https://github.com/microsoft/pipelines-appservice-lib/blob/master/packages/secret-parser/src/index.ts) to avoid leaking the credentials in output.

However, if the same secrets is used outside of that action (e.g. in a run statement) I understand the concern. Same goes for using `{{ github }}` expression in workflows.

You can also consider creating an issue in the Azure/login repo to raise the concern on this, and see if there are ways to improve the use of the action.

**Comment by torivara** [comment]
Aha, I did not know that. Thank you for the reply, @matsest 🙂 I am using a different method for logging in at the moment, with support for specifying credentials in separate secrets. I'll assume the developers of azlogin action is aware of this, and thinks it is not a major issue.

This is probably a reasonably low risk configuration, and I will close the issue as my question has been answered.
